### ISSUE TITLE
recommendations for running sophie on new models

### ISSUE THREAD

**Issue by taylorreiter** [greenelab/generic-expression-patterns#105]
Hello! I have read through the documentation provided in this repository, but am still curious what the best practice recommendation is around running SOPHIE in the context of a new model. When one has a specific experiment(s) of interest that they're seeking to identify generic/specific expression patterns, I'm wondering if it's best to train the new model including or excluding those samples. In this case, I think I'll have between 600-2000 input samples to train the model on, and about 55 samples that I'll want to use to pull out specific and generic gene expression patterns. Does it matter if those 55 samples are used to build the model?

**Comment by ajlee21** [comment]
Great question. It isn't required that the target experiment (i.e. your 55 samples) in are included in the training set. The only requirement is that the feature space (i.e. the genes) are the same in order to perform the latent space embedding which is performed to simulate the data.

As long as the held out 55 samples are "represented" in the training set then you should be ok -- i.e. if your training set contains are non-cancer samples but your target/held out experiment is cancer. Then SOPHIE will likely say that many genes are specific since it has not seen something like your target set in its training.

**Comment by taylorreiter** [comment]
Thank you!

**Comment by ajlee21** [comment]
Addressed in https://github.com/greenelab/sophie/pull/3
