### ISSUE TITLE
unclear input requirement for new models: `scaler_filename`

### ISSUE THREAD

**Issue by taylorreiter** [greenelab/generic-expression-patterns#106]
The notebook `new_model_experiment/1_process_and_train_vae.ipynb` states that a scaler transform, designated by `scaler_filename`, used to normalize the training compendium is required in the config file. It further states that this can be found in the `data` directory within the analysis folder.

```
4. Scaler transform (`scaler_filename`) used to normalize the training compendium. This can be found in the `data/` directory within the analysis folder.
```
https://github.com/greenelab/generic-expression-patterns/blob/master/new_model_experiment/1_process_and_train_vae.py#L43

I'm not sure from these instructions what this file should be. I see that different analysis directories contain these files (e.g. [scaler_transform_pseudomonas.pickle](https://github.com/greenelab/generic-expression-patterns/blob/master/pseudomonas_analysis/data/scaler_transform_pseudomonas.pickle)). Can I use this scaler transform for my new data? If not, how do I create a new one? Or, is this just an output file name? If it is an output file name, does it have to have `data/` as the output folder, or can this be named anything?

**Comment by ajlee21** [comment]
Another place for me to clarify wording.

[Here](https://github.com/greenelab/generic-expression-patterns/blob/master/pseudomonas_analysis/data/scaler_transform_pseudomonas.pickle) is an example of the scaler file that is created to scale the input data so that the features/genes are within the same range - in this case each gene is scaled to be between 0-1. This scaling is used to allow us to "de-scale" the simulated experiments in order to perform DE analysis.

If you are training a new model. Then the value in the config file for `scaler_filename` should be the filename that the pickle file that is generated by [this function](https://github.com/greenelab/generic-expression-patterns/blob/fa56a2df12c1b17e4dd0a03fd3693d51e8f31bbd/new_model_experiment/1_process_and_train_vae.py#L101) will be saved to. 

However if you're using an existing (already trained) model. Then this `scaler_filename` should be the location where the scaler is stored in the following locations: Recount (`human_general_analysis/data/*.pickle`), Powers et. al. (`human_cancer_analysis/data/*pickle`), P. aeruginosa (`pseudomonas_analysis/data/*pickle`)

**Comment by taylorreiter** [comment]
thank you!

**Comment by ajlee21** [comment]
Addressed in https://github.com/greenelab/sophie/pull/3
